import assert from "node:assert/strict";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const mimeTypes = new Map([
  [".html", "text/html; charset=utf-8"],
  [".js", "text/javascript; charset=utf-8"],
  [".css", "text/css; charset=utf-8"],
]);

const server = createServer(async (request, response) => {
  try {
    const url = new URL(request.url, "http://127.0.0.1");
    const path = url.pathname === "/" ? "/index.html" : url.pathname;
    const filePath = normalize(join(root, path));
    if (!filePath.startsWith(root)) {
      response.writeHead(403);
      response.end("Forbidden");
      return;
    }
    const body = await readFile(filePath);
    response.writeHead(200, { "content-type": mimeTypes.get(extname(filePath)) ?? "text/plain" });
    response.end(body);
  } catch {
    response.writeHead(404);
    response.end("Not found");
  }
});

await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const { port } = server.address();
const baseUrl = `http://127.0.0.1:${port}`;

try {
  const control = await fetch(`${baseUrl}/index.html`).then((response) => response.text());
  const overlay = await fetch(`${baseUrl}/overlay.html?channel=test&debug=1`).then((response) => response.text());
  const controlApp = await fetch(`${baseUrl}/src/ui/control-app.js`).then((response) => response.text());
  const baseCss = await fetch(`${baseUrl}/styles/base.css`).then((response) => response.text());
  const controlCss = await fetch(`${baseUrl}/styles/control.css`).then((response) => response.text());
  const overlayCss = await fetch(`${baseUrl}/styles/overlay.css`).then((response) => response.text());
  const historyView = await fetch(`${baseUrl}/src/ui/history-view.js`).then((response) => response.text());
  const diagnosticsView = await fetch(`${baseUrl}/src/ui/diagnostics-view.js`).then((response) => response.text());
  const controlForm = await fetch(`${baseUrl}/src/ui/control-form.js`).then((response) => response.text());
  const optionAccess = await fetch(`${baseUrl}/src/core/option-access.js`).then((response) => response.text());
  const obsConnectionMonitor = await fetch(`${baseUrl}/src/ui/obs-connection-monitor.js`).then((response) => response.text());
  const premiumLocks = await fetch(`${baseUrl}/src/ui/premium-locks.js`).then((response) => response.text());
  const twitchVisualStatus = await fetch(`${baseUrl}/src/ui/twitch-visual-status-view.js`).then((response) => response.text());
  const settingsPresets = await fetch(`${baseUrl}/src/ui/settings-presets.js`).then((response) => response.text());
  const externalEmotes = await fetch(`${baseUrl}/src/chat/external-emotes.js`).then((response) => response.text());
  const stressFixtures = await fetch(`${baseUrl}/src/chat/stress-fixtures.js`).then((response) => response.text());
  const simulationActions = await fetch(`${baseUrl}/src/ui/simulation-actions.js`).then((response) => response.text());
  const twitchSessionController = await fetch(`${baseUrl}/src/twitch/session-controller.js`).then((response) => response.text());
  const twitchChatAssets = await fetch(`${baseUrl}/src/twitch/chat-assets.js`).then((response) => response.text());

  assert.match(control, /ChatPulse/);
  assert.match(control, /URL OBS/);
  assert.match(control, /copy-url-button/);
  assert.match(control, /Copier/);
  assert.match(control, /Messages de test/);
  assert.match(control, /Lancer stress test/);
  assert.equal(control.includes("Tests avancés"), false);
  assert.equal(control.includes("action-disclosure"), false);
  assert.match(control, /Couleur principale de l'overlay/);
  assert.match(control, /Réglages de base/);
  assert.match(control, /Profils rapides/);
  assert.match(control, /id="preset-buttons"/);
  assert.match(control, /data-preset-id="just-chatting"/);
  assert.match(control, /data-preset-id="fps"/);
  assert.match(control, /data-preset-id="mobile"/);
  assert.match(control, /data-preset-id="minimal"/);
  assert.match(control, /data-preset-id="big-screen"/);
  assert.match(control, /messages plus lisibles, plus confortables/i);
  assert.match(control, /ne pas cacher le jeu/i);
  assert.match(control, /meilleure lisibilité sur petit écran/i);
  assert.match(control, /overlay léger, peu visible/i);
  assert.match(control, /scène 16:9 avec plus d'espace/i);
  assert.match(control, /id="preset-status"/);
  assert.match(control, /Connexion Twitch/);
  assert.match(control, /id="twitch-client-id-input"/);
  assert.match(control, /Connecter Twitch/);
  assert.match(control, /Démarrer le live/);
  assert.match(control, /Flux des messages/);
  assert.match(control, /id="lifetime-input"[^>]+min="5000"/);
  assert.match(control, /id="lifetime-number-input"[^>]+min="5"/);
  assert.match(control, /Placement OBS/);
  assert.match(control, /Apparence des cartes/);
  assert.match(control, /compact-settings/);
  assert.match(control, /Options OBS/);
  assert.match(control, /id="twitch-visuals-input"/);
  assert.match(control, /Badges et emotes Twitch officiels/);
  assert.match(control, /option gratuite/);
  assert.match(control, /id="external-emotes-input"/);
  assert.match(control, /Emotes externes 7TV, BTTV et FFZ/);
  assert.match(control, /Visuels Twitch/);
  assert.match(control, /id="visual-status-list"/);
  assert.match(control, /Nombre messages visible/);
  assert.match(control, /id="max-messages-input"[^>]+min="1"/);
  assert.match(control, /id="max-messages-input"[^>]+max="24"/);
  assert.match(control, /id="max-messages-number-input"[^>]+min="1"/);
  assert.match(control, /id="max-messages-number-input"[^>]+max="24"/);
  assert.match(control, /Valeur précise/);
  assert.match(control, /id="lifetime-number-input"/);
  assert.match(control, /id="max-messages-number-input"/);
  assert.match(control, /id="font-scale-number-input"/);
  assert.match(control, /id="gap-number-input"/);
  assert.match(control, /id="opacity-number-input"/);
  assert.match(control, /id="radius-number-input"/);
  assert.match(control, /Sens d'apparition/);
  assert.match(control, /class="wide-field"/);
  assert.match(control, /Position dans OBS/);
  assert.match(control, /<label class="wide-field">\s*Position dans OBS\s*<select id="position-input"/);
  assert.match(control, /Tester alerte OBS/);
  assert.match(control, /Simuler suppression/);
  assert.match(control, /Activer AutoMod/);
  assert.match(control, /Simuler alerte/);
  assert.match(control, /Simuler erreur/);
  const leftColumn = control.slice(
    control.indexOf('<div class="control-column left-column">'),
    control.indexOf('<div class="control-column right-column">'),
  );
  const rightColumn = control.slice(
    control.indexOf('<div class="control-column right-column">'),
    control.indexOf('</main>'),
  );
  const previewSection = rightColumn.slice(
    rightColumn.indexOf('<section class="workspace-panel preview-panel'),
    rightColumn.indexOf('<section class="workspace-panel status-panel'),
  );
  assert.match(leftColumn, /setup-panel[\s\S]*history-panel/);
  assert.match(rightColumn, /preview-panel[\s\S]*status-panel[\s\S]*log-panel/);
  assert.match(previewSection, /<div class="action-stack preview-actions">[\s\S]*<div class="preview-block">/);
  assert.equal(leftColumn.includes("action-stack"), false);
  assert.match(control, /Messages reçus/);
  assert.match(control, /0 en attente/);
  assert.match(control, /0 supprimé/);
  assert.match(control, /0 bloqué/);
  assert.match(control, /Modération freemium/);
  assert.match(control, /Protection active/);
  assert.match(overlay, /Mode démo/);
  assert.match(controlApp, /createOverlayUrl/);
  assert.match(controlApp, /createControlForm/);
  assert.match(controlApp, /PREMIUM_OPTION_LOCKS/);
  assert.match(controlApp, /normalizeOptionLocks/);
  assert.match(controlApp, /createPremiumLockController/);
  assert.match(controlApp, /premiumLockController\.apply\(\)/);
  assert.match(controlApp, /createTwitchVisualStatusView/);
  assert.match(controlApp, /twitch:visuals/);
  assert.match(controlApp, /createObsConnectionMonitor/);
  assert.match(controlApp, /applySettingsPreset/);
  assert.match(controlApp, /getSettingsPreset/);
  assert.match(controlApp, /createSimulationActions/);
  assert.match(controlApp, /createTwitchSessionController/);
  assert.equal(controlApp.includes("buildTwitchAuthUrl"), false);
  assert.equal(controlApp.includes("readTwitchTokenFromUrl"), false);
  assert.equal(controlApp.includes("createTwitchEventSubSource"), false);
  assert.match(controlApp, /startTwitchLive/);
  assert.match(controlApp, /connectTwitchOAuth/);
  assert.match(controlApp, /copyOverlayUrl/);
  assert.match(controlApp, /formatOverlayUrl/);
  assert.match(controlApp, /dataset\.fullUrl/);
  assert.match(controlApp, /fallbackCopyText/);
  assert.match(controlApp, /createHistoryView/);
  assert.match(controlApp, /createDiagnosticsView/);
  assert.equal(controlApp.includes("function runStressTest"), false);
  assert.equal(controlApp.includes("function emitObsNotification"), false);
  assert.equal(controlApp.includes("function syncPreciseInputs"), false);
  assert.equal(controlApp.includes("function handlePreciseInput"), false);
  assert.match(controlApp, /setPreviewCapacityHeight/);
  assert.match(controlApp, /--preview-target-height/);
  assert.match(controlApp, /previewHeightForCapacity/);
  assert.match(controlApp, /chat:moderation/);
  assert.match(controlApp, /applyModeration/);
  assert.match(controlApp, /moderationLogMessage/);
  assert.match(controlApp, /messageCount\.textContent = `\$\{stats\.visible\} message/);
  assert.match(controlApp, /displayedCount\.textContent = `\$\{stats\.received\} reçu/);
  assert.equal(controlApp.includes("function simulateDeletedMessage"), false);
  assert.equal(controlApp.includes("getVisibleMessages"), false);
  assert.equal(controlApp.includes("function toggleAutomodSimulation"), false);
  assert.equal(controlApp.includes("function emitAutomodProbe"), false);
  assert.match(controlApp, /automodSimulation: simulationActions\.isAutomodEnabled\(\)/);
  assert.match(controlApp, /writeLiveConfig\(globalThis\.localStorage/);
  assert.match(controlApp, /overlayConfig: nextConfig/);
  assert.equal(controlApp.includes("function updateObsConnectionStatus"), false);
  assert.match(controlApp, /sendLiveCommand\("test-message"/);
  assert.equal(controlApp.includes('sendLiveCommand("stress-test"'), false);
  assert.equal(controlApp.includes('sendLiveCommand("delete-message"'), false);
  assert.equal(controlApp.includes("function shouldBlockByAutomod"), false);
  assert.equal(controlApp.includes("function randomAutomodThreshold"), false);
  assert.match(controlApp, /refreshLivePanels/);
  assert.equal(controlApp.includes('source: "moderation-test"'), false);
  assert.equal(controlApp.includes('message.source === "moderation-test"'), false);
  assert.equal(controlApp.includes("renderer.clear();"), false);
  assert.match(controlApp, /updatePresetSelection/);
  assert.match(controlApp, /aria-pressed/);
  assert.equal(controlApp.includes("Math.random"), false);
  assert.equal(controlApp.includes("Message #1 affiché dans l'overlay"), false);
  assert.match(controlApp, /renderMessageHistory/);
  assert.match(controlApp, /setOptions/);
  assert.match(historyView, /renderHistoryItem/);
  assert.match(historyView, /toggleModeratedHistoryReveal/);
  assert.match(diagnosticsView, /createDiagnosticsView/);
  assert.match(controlForm, /createControlForm/);
  assert.match(controlForm, /enforceOptionLocks/);
  assert.match(controlForm, /optionLocks/);
  assert.match(controlForm, /function hydrate/);
  assert.match(controlForm, /function collect/);
  assert.match(controlForm, /twitchVisuals/);
  assert.match(controlForm, /externalEmotes/);
  assert.match(controlForm, /function handlePreciseInput/);
  assert.match(controlForm, /function syncPreciseInputs/);
  assert.match(obsConnectionMonitor, /createObsConnectionMonitor/);
  assert.match(obsConnectionMonitor, /writeLiveCommand/);
  assert.match(obsConnectionMonitor, /readOverlayHeartbeat/);
  assert.match(obsConnectionMonitor, /readCommandAck/);
  assert.match(obsConnectionMonitor, /isOverlayHeartbeatFresh/);
  assert.match(obsConnectionMonitor, /createOverlayConfigHash/);
  assert.match(obsConnectionMonitor, /pendingLiveCommandId/);
  assert.match(obsConnectionMonitor, /diagnostics\.snapshot\(\)\.obs\?\.message/);
  assert.match(obsConnectionMonitor, /Commande envoyée à OBS\. En attente de confirmation/);
  assert.match(obsConnectionMonitor, /OBS connecté/);
  assert.match(obsConnectionMonitor, /Réglages OBS différents/);
  assert.match(optionAccess, /LOCKABLE_OPTION_DEFINITIONS/);
  assert.match(optionAccess, /PREMIUM_OPTION_LOCKS/);
  assert.match(optionAccess, /enforceOptionLocks/);
  assert.match(optionAccess, /elementKeys/);
  assert.match(premiumLocks, /createPremiumLockController/);
  assert.match(premiumLocks, /premium-locked/);
  assert.match(premiumLocks, /premium-lock-badge/);
  assert.match(premiumLocks, /aria-disabled/);
  assert.match(twitchVisualStatus, /createTwitchVisualStatusView/);
  assert.match(twitchVisualStatus, /OAuth Twitch/);
  assert.match(twitchVisualStatus, /Badges officiels/);
  assert.match(settingsPresets, /SETTING_PRESETS/);
  assert.match(settingsPresets, /applySettingsPreset/);
  assert.match(settingsPresets, /Just Chatting/);
  assert.match(settingsPresets, /Grand écran/);
  assert.match(settingsPresets, /messageLifetimeMs/);
  assert.equal(settingsPresets.includes("twitchClientId"), false);
  assert.match(stressFixtures, /STRESS_TEST_TOTAL/);
  assert.match(stressFixtures, /createStressTestMessage/);
  assert.match(stressFixtures, /emitStressTestMessages/);
  assert.match(stressFixtures, /moderator/);
  assert.match(stressFixtures, /vip/);
  assert.match(stressFixtures, /subscriber/);
  assert.match(stressFixtures, /emoteId/);
  assert.match(externalEmotes, /createExternalEmoteAssets/);
  assert.match(externalEmotes, /7tv\.io\/v3/);
  assert.match(externalEmotes, /betterttv\.net\/3\/cached/);
  assert.match(externalEmotes, /frankerfacez\.com\/v1\/room/);
  assert.match(simulationActions, /createSimulationActions/);
  assert.match(simulationActions, /emitStressTestMessages/);
  assert.match(simulationActions, /function runStressTest/);
  assert.match(simulationActions, /function emitObsNotification/);
  assert.match(simulationActions, /function simulateDeletedMessage/);
  assert.match(simulationActions, /function toggleAutomodSimulation/);
  assert.match(simulationActions, /function shouldBlockByAutomod/);
  assert.match(simulationActions, /function randomAutomodThreshold/);
  assert.match(simulationActions, /getVisibleMessages/);
  assert.match(simulationActions, /sendLiveCommand\("stress-test"/);
  assert.match(simulationActions, /sendLiveCommand\("delete-message"/);
  assert.match(simulationActions, /source: "moderation-test"/);
  assert.match(simulationActions, /message\.source === "moderation-test"/);
  assert.match(simulationActions, /aria-pressed/);
  assert.match(simulationActions, /AutoMod activé/);
  assert.match(simulationActions, /Désactiver AutoMod/);
  assert.match(simulationActions, /Math\.random/);
  assert.match(twitchSessionController, /createTwitchSessionController/);
  assert.match(twitchSessionController, /buildTwitchAuthUrl/);
  assert.match(twitchSessionController, /readTwitchTokenFromUrl/);
  assert.match(twitchSessionController, /createTwitchEventSubSource/);
  assert.match(twitchSessionController, /chatpulse-twitch-token/);
  assert.match(twitchChatAssets, /createTwitchChatAssets/);
  assert.match(twitchChatAssets, /chat\/badges\/global/);
  assert.match(twitchChatAssets, /chat\/badges\?broadcaster_id=/);
  assert.match(controlCss, /grid-template-columns: minmax\(440px, 0\.95fr\) minmax\(560px, 1\.05fr\)/);
  assert.match(controlCss, /\.control-column/);
  assert.match(controlCss, /\.left-column \{ grid-column: 1; \}/);
  assert.match(controlCss, /\.right-column \{ grid-column: 2; \}/);
  const compactMedia = controlCss.slice(
    controlCss.indexOf("@media (max-width: 1040px)"),
    controlCss.indexOf("@media (max-width: 900px)"),
  );
  assert.match(compactMedia, /grid-template-columns: minmax\(360px, 0\.95fr\) minmax\(420px, 1\.05fr\)/);
  assert.equal(compactMedia.includes('"status status"'), false);
  assert.match(controlCss, /@media \(max-width: 720px\)/);
  assert.match(controlCss, /font-size: 0\.9rem/);
  assert.match(controlCss, /line-height: 1\.35/);
  assert.match(controlCss, /\.settings-group/);
  assert.match(controlCss, /\.settings-grid/);
  assert.match(controlCss, /\.preset-grid/);
  assert.match(controlCss, /\.preset-tooltip/);
  assert.match(controlCss, /\.preset-grid button:hover \.preset-tooltip/);
  assert.match(controlCss, /\.preset-grid button:focus-visible \.preset-tooltip/);
  assert.match(controlCss, /\.preset-status/);
  assert.match(controlCss, /\.preset-grid button\[aria-pressed="true"\]/);
  assert.match(controlCss, /\.premium-locked/);
  assert.match(controlCss, /\.premium-lock-badge/);
  assert.match(controlCss, /\.wide-field/);
  assert.match(controlCss, /\.settings-disclosure summary::after/);
  assert.match(controlCss, /\.settings-disclosure summary:hover/);
  assert.match(controlCss, /\.settings-disclosure summary:focus-visible/);
  assert.match(controlCss, /\.compact-settings/);
  assert.match(controlCss, /min-height: 119px/);
  assert.match(controlCss, /grid-template-rows: auto 1fr/);
  assert.match(controlCss, /var\(--preview-target-height,\s*440px\)/);
  assert.match(controlCss, /min-height: 160px/);
  assert.match(controlCss, /\.moderation-block/);
  assert.match(controlCss, /\.history-deleted/);
  assert.match(controlCss, /\.history-blocked/);
  assert.match(controlCss, /\.history-notification/);
  assert.match(controlCss, /\.history-revealable/);
  assert.match(controlCss, /\.history-revealed/);
  assert.match(controlCss, /align-items: start/);
  assert.match(controlCss, /align-content: start/);
  assert.match(controlCss, /input:not\(\[type="checkbox"\]\):not\(\[type="range"\]\)/);
  assert.match(controlCss, /min-height: 24px/);
  assert.match(controlCss, /white-space: nowrap/);
  assert.match(controlCss, /grid-template-columns: minmax\(0, 1fr\) auto/);
  assert.match(baseCss, /-webkit-font-smoothing: antialiased/);
  assert.match(baseCss, /transition: opacity 420ms ease, transform 420ms ease, filter 420ms ease/);
  assert.match(baseCss, /\.chat-header/);
  assert.match(baseCss, /\.chat-badge-mod/);
  assert.match(baseCss, /\.chat-badge-vip/);
  assert.match(baseCss, /\.chat-badge-sub/);
  assert.match(baseCss, /\.chat-badge-image/);
  assert.match(baseCss, /\.chat-emote/);
  assert.match(baseCss, /\.chat-emote-external/);
  const overlayApp = await fetch(`${baseUrl}/src/ui/overlay-app.js`).then((response) => response.text());
  assert.match(overlayApp, /stressMode/);
  assert.match(overlayApp, /emitStressTestMessages/);
  assert.match(overlayApp, /LIVE_COMMAND_STORAGE_KEY/);
  assert.match(overlayApp, /writeOverlayHeartbeat/);
  assert.match(overlayApp, /writeCommandAck/);
  assert.match(overlayApp, /sendOverlayHeartbeat/);
  assert.match(overlayApp, /ackLiveCommand/);
  assert.match(overlayApp, /setInterval\(sendOverlayHeartbeat, 2000\)/);
  assert.match(overlayApp, /applyLiveCommand/);
  assert.match(overlayApp, /test-message/);
  assert.match(overlayApp, /obs-notification/);
  assert.match(overlayApp, /delete-message/);
  assert.match(overlayApp, /Réglages OBS mis à jour sans rechargement/);
  assert.match(overlayApp, /automod: params\.get\("automod"\)/);
  assert.match(overlayApp, /LIVE_CONFIG_STORAGE_KEY/);
  assert.match(overlayApp, /addEventListener\("storage"/);
  assert.match(overlayApp, /applyLiveConfig/);
  assert.match(overlayApp, /emitAutomodProbe/);
  assert.match(overlayApp, /banword/);
  assert.match(overlayApp, /shouldBlockByAutomod/);
  assert.match(overlayApp, /AutoMod OBS/);
  assert.match(overlayApp, /stats\.blocked/);
  assert.match(overlayApp, /bloqué/);
  assert.match(overlayApp, /applyVisualConfig/);
  assert.match(overlayApp, /maxMessages/);
  assert.match(overlayApp, /en attente/);
  assert.match(overlayCss, /background: transparent/);
  assert.match(overlayCss, /max-height: 100%/);
  assert.match(overlayCss, /overflow: hidden/);
  assert.equal(control.includes("access_token"), false);
  assert.equal(overlay.includes("access_token"), false);

  console.log("PASS browser smoke verified");
} finally {
  await new Promise((resolve) => server.close(resolve));
}

